### List all orders with a limit of 10
GET http://localhost:8000/api/orders?limit=10
Content-Type: application/json

### Get a orders by ID
GET http://localhost:8000/api/orders/1
Content-Type: application/json

### Create a new orders
POST http://localhost:8000/api/orders
Content-Type: application/json

{
  "restaurant_id": 1,
  "delivery_address_id": 1,
  "user_id": 1,
  "driver_id": 1,
  "price": 2000,
  "discount": 100,
  "final_price": 1900,
  "comment": "welcome back"
}

### Update a orders by ID
PUT http://localhost:8000/api/orders/9
Content-Type: application/json

{
  "final_price": 1950
}

### Delete a orders by ID
DELETE http://localhost:8000/api/orders/1
Content-Type: application/json
